name: Build and Test ATS3

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

env:
  ATS2_VERSION: 0.4.2

jobs:
  build-and-test-cygwin:
    runs-on: "windows-latest"
    defaults:
      run:
        shell: C:\tools\cygwin\bin\bash.exe --login -o igncr '{0}'
    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: make autoconf automake gcc-core libtool intltool pkg-config git libgc-devel libgmp-devel wget

      - name: Set environment variables
        run: |
          echo "PATSHOME=$GITHUB_WORKSPACE/ATS2" >> $GITHUB_ENV
          echo "XATSHOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "${{ env.PATSHOME }}/bin" >> $GITHUB_PATH

      - name: Install ATS2
        run: ${GITHUB_WORKSPACE}/.github/install-ats2.sh ${{ env.ATS2_VERSION }} ${{ env.PATSHOME }}

      - name: Build ATS2
        run: ${GITHUB_WORKSPACE}/.github/build.sh

      - name: Run Tests
        run: ${GITHUB_WORKSPACE}/.github/test.sh

  build-and-test-linux:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libgc-dev libgmp-dev
          version: 1.0

      - name: Set environment variables
        run: |
          echo "PATSHOME=$GITHUB_WORKSPACE/ATS2" >> $GITHUB_ENV
          echo "XATSHOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
          echo "${{ env.PATSHOME }}/bin" >> $GITHUB_PATH

      - name: Install ATS2
        run: ${GITHUB_WORKSPACE}/.github/install-ats2.sh "$ATS2_VERSION" "${{ env.PATSHOME }}"

      - name: Print PATSHOME/bin
        run: echo "$(ls)" >> $GITHUB_STEP_SUMMARY

      - name: Build ATS3
        run: ${GITHUB_WORKSPACE}/.github/build.sh

      - name: Run Tests
        run: ${GITHUB_WORKSPACE}/.github/test.sh
